version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: privategpt
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: privategpt
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  auth-service:
    build: ./docker/auth
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://privategpt:secret@db:5432/privategpt
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8001:8000"

  knowledge-service:
    build: ./docker/knowledge
    depends_on:
      - db
      - redis
      - weaviate
    environment:
      DATABASE_URL: postgresql://privategpt:secret@db:5432/privategpt
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8002:8000"

  weaviate:
    image: semitechnologies/weaviate:1.22.0
    restart: unless-stopped
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
    ports:
      - "8080:8080"

  ui-service:
    build: ./docker/ui
    depends_on:
      - auth-service
      - knowledge-service
    ports:
      - "8501:8501"

  tests:
    build:
      context: ..
      dockerfile: v2/docker/tests/Dockerfile
    depends_on:
      - auth-service
    command: pytest -q v2/tests

volumes:
  db-data:
