api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":8080"
  traefik:
    address: ":8081"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

log:
  level: INFO 