# Metricbeat configuration

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

# Default modules (can be customized in modules.d)
metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    # - filesystem # Uncomment if needed
    # - fsstat # Uncomment if needed
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  processes: ['.*'] # Monitor all processes

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  # protocol: "https"
  # username: "elastic"
  # password: "changeme"

# logging.level: debug # Optional: for debugging Metricbeat 