# Filebeat setup configuration - for dashboard installation only

filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata: ~

- type: filestream
  id: my-app-logs
  paths:
    - /var/log/legal-ai/**/*.log
    - /var/log/legal-ai/**/*.jsonl
  parsers:
    - ndjson:
        keys_under_root: true
        add_error_key: true
        message_key: message
  fields:
    log_type: privategpt_app

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# For setup, send directly to Elasticsearch
output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601" 